### ISSUE TITLE
Project has gone stale

### ISSUE THREAD

**Issue by maxb2** [Blackflighter/donjon-painter#2]
It seems this project has gone stale. @Blackflighter has been inactive for at least a year. I made the [donjon-painter](https://github.com/donjon-painter/donjon-painter) organization to host the updated project. I invited @Blackflighter to be a member when he comes back.

**Comment by Blackflighter** [comment]
Apologies for missing that invitation - I haven't really been doing all that much with this as of late, but I'd be glad to join, albeit belatedly.

**Comment by maxb2** [comment]
Awesome!

**Comment by Blackflighter** [comment]
Might you be able to send another invitation? The previous one has expired.

**Comment by maxb2** [comment]
Sent

**Comment by Blackflighter** [comment]
And all joined up! Alrighty, time to update those packages...
